block_size: 21
confidence: 0.1
constant: 10
data_path: ../data/cow5/
diam: 27
filter_type: 1
fps: 4.5
im_width: 700
input_type: 0
max_disappeared: 10
max_distance: 1000
model: 1
model_path: ./model_checkpoint
output_path: ./output_checkpoints
resize: true
sigma_color: 150
sigma_space: 100
skip_frames: 10
thresh: 0.25
